linters:
  enable-all: true
  disable:
    - copyloopvar
    - depguard
    - err113
    - execinquery
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - godox
    - gofumpt
    - gomnd
    - inamedparam
    - intrange
    - ireturn
    - lll
    - maintidx
    - mnd
    - nestif
    - nilnil
    - nlreturn
    - paralleltest
    - revive
    - tagalign
    - testpackage
    - tparallel
    - varnamelen
    - wrapcheck
    - wsl

linters-settings:
  gosec:
    excludes:
      # 0644 permissions on created files seem reasonable for this use-case
      - G306

  govet:
    enable-all: true
    disable:
      # fixing this is low-priority for this library
      - fieldalignment
      # we test invalid struct tags intentionally
      - structtag